service:
  name: auction-service

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

resources:
  # DynamoDB
  - ${file(resources/dynamodb-tables.yml)}
    
custom:
  dynamodb:
    stages:
        - dev
    start:
        port: 8000
        inMemory: true
        migrate: true

functions:
  createAuction:
    handler: src/infrastructure/lambdas/api/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
