service:
  name: auction-service

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  
functions:
  createAuction:
    handler: src/infrastructure/lambdas/api/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
